### ISSUE TITLE
Impliment progress bar UI

### ISSUE THREAD

**Issue by milivayuz** [milivayuz/VAYUZ_Career#294] opened 2024-05-29 08:16 UTC
<img width="959" alt="image" src="https://github.com/milivayuz/VAYUZ_Career/assets/156641922/a9701313-8204-4cec-aa99-a7748633e8ac">

**Comment by vinayak-vayuz** [comment] 2024-05-31 13:24
Duplicate of #244

**Closed as completed** 2024-06-01 04:47 UTC
Labels: duplicate, Web, UI, People Group, Post Job, Review Required, UAT-1
